### PR TITLE
[F] Edge browser missing selection graphics

### PR DESCRIPTION
**Pull request by bossloper**
Radio/check and dropdown fields missing selected state and dropdown arrow.
https://github.com/evolution-cms/evolution/issues/211

Similar issue to here: https://github.com/zurb/foundation-sites/issues/8545#issuecomment-207209608
Edge need urls in double quotes. Fixed by switching double and single quote around.

### CODE REVIEW

**Comment by 64j** [comment]
@bossloper does this solve your problem in the browser Edge?

**Comment by bossloper** [comment]
yes

**Comment by 64j** [comment]
@bossloper this miracle browser Edge :)

**Comment by 64j** [comment]
fixed https://github.com/evolution-cms/evolution/commit/af7ab93436b865550d21ebe17a57792dc87baf1c

**Pull request closed without merging**
