### PR TITLE
[I] Ajax-API for publish/delete resources in welcome.static

### PR DESCRIPTION
**Pull request by Deesen**
Related to #406

- issues with activated "global tabs"
- confirmation-dialog needs to be added

Example usage in welcome.static.php :
```
<a data-ajaxaction="delete.res" data-id="10" data-element="element_id">Delete Resource</a>
<a data-ajaxaction="publish.res" data-id="10" data-element="element_id">Unpublish Resource</a>

<tr id="element_id" class="deleted unpublished">
   <td>...</td>
   <td>...</td>
</tr>
```

@dmi3yy @64j What do you think about this approach? Maybe you have a better idea?

### CODE REVIEW

**Comment by 64j** [comment]
@Deesen 
If make Ajax in this way, maybe us need to create a rule for the "data-ajax action" commands.

data-ajax = "< object > / < action > ? params"
href = "< method > : < object > / < action > ? params"
The separator can be any
And can call any callback after
```
<span data-ajax="resource/delete?id=10&callback=resourceDeleted">Delete Resource</span>

<span data-ajax="resource/set?id=10&parent=1">Move Resource</span>

<span data-ajax="chunk/delete?id=10&callback=chunkDeleted">Delete Chunk</span>

or

<a href="ajax:resource/delete?id=10&callback=resourceDeleted">Delete Resource</a>

<a href="ajax:resource/set?id=10&parent=1">Move Resource</a>

<a href="ajax:chunk/delete?id=10&callback=chunkDeleted">Delete Chunk</a>
```

What do you think?

**Comment by Deesen** [comment]
@AgelxNash Thanks! I generally did not know intval() is so slow!

I think a rule makes sense, as well as a callback. If we have a rule I think `<a href="ajax:...` makes no sense as we probably need the href as fallback in case ajaxActions are not available.

You think 1 param like data-ajax is enough, instead of multiple params like data-id, data-callback etc? I think multiple params make it easier for all kind of developers, especially if more params will be added in future.

**Comment by 64j** [comment]
@Deesen 
Parameters in the form of url, can be used not only for Ajax, but also as direct queries.
In my opinion, need to start with the parser, remove garbage from code, and add a normal restApi, and then already on Ajax.

**Comment by Deesen** [comment]
Sounds like a plan 👍 . If I can be of any help, let me know.

**Pull request closed without merging**
