### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by yama**
Hello,
I want to implement the draft posting function used in the Japanese version.
Organize complex code for that.
Thanks.

### CODE REVIEW

**Comment by yama** [comment]
@Dmi3yy @Ser1ous 
I will reassemble the pull request later.
This pull request closes.

**Comment by Dmi3yy** [comment]
Plz send with smoller

**Comment by Dmi3yy** [comment]
Plz send smaller one :) will be easy to check

**Comment by yama** [comment]
@Dmi3yy 
thank you. But isn't it better not to use sprintf?
and, editorconfig can create a new pull request.

**Pull request closed without merging**
