### PR TITLE
installer code cleanup

### PR DESCRIPTION
**Pull request by yama**
table_prefix() and sql_escape() are temporary functions.

### CODE REVIEW

**Comment by 64j** [comment]
@yama 
Why use functions that will slow down?

http://sandbox.onlinephpfunctions.com/code/958aa91c2134479fac1c287e990b3cb15dfd6910

**Comment by yama** [comment]
It is common sense that sprintf is slower than concatenation of variables. Of course, I understand it.

http://sandbox.onlinephpfunctions.com/code/958aa91c2134479fac1c287e990b3cb15dfd6910
Actually check.

0.000012874603271484 sec - sprintf
0.0000019073486328125 sec - concat Variables

Certainly, sprintf is slower 0.00001 seconds, it's slow.
But can we experience this as "slow"?
If we feel that sprintf is slow, using Query Builder will be more slower.
Of course, DBAPI is also slow.

But at least I think it is not good to assemble complex SQL statements just by only concatenation of variables.
For ex, Security issues and unknown overhead, etc.
If we do not cleanup the source code, those problems can not be found out.

**Comment by yama** [comment]
https://github.com/evolution-cms/evolution/pull/1078/commits/a39c5920c34093796a7883506780072528ed41ba
It becomes easy to look at the value input to DB.

**Comment by yama** [comment]
If we want to create an evolving system, I think the improvement of the installer is essential.
This is evolution cms?
I think so

**Pull request merged**
