### PR TITLE
Create snippet.DocCount.php

### PR DESCRIPTION
**Pull request by kanstudio**
The new snippet, which counts a number of daughter documents. It's well suited for a little web store.
Available parameters:
&parent - ID of the parent document
&templates - IDs of the daughter document templates
&depth - nesting level (<0, 0, >9 == 10, max)
&published - which documents will be counted (0 - unpublished || 1 - published || 2 - all)

What about speed - snippet does only 1 query to database with any &depth values!

Examples:
```
[[DocCount? &parent=`[*id*]` &templates=`0` &depth=`1` &published=`1`]]  // default values
[[DocCount]]  // will return the same as the previous example
[[DocCount? &templates=`2,3,5` &depth=`0` &published=`2`]]  // will return the count 
of all children with template IDs 2,3 or 5 of the current document.
```

And I recommend this snippet for using with <@SYNTAX>, when you need to display some HTML in case the daughter documents exist and are published.

### CODE REVIEW

**Comment by 64j** [comment]
@kanstudio 

http://docs.evo.im/en/04_extras/dlmenu.html
```
[[DLMenu?
&parents=`0`
&countChildren=`1`
]]
```

**Comment by kanstudio** [comment]
> @kanstudio
> 
> http://docs.evo.im/en/04_extras/dlmenu.html
> 
> ```
> [[DLMenu?
> &parents=`0`
> &countChildren=`1`
> ]]
> ```

Have you tested it? Instead of integer value the html-code of the menu is displayed.

I managed to get the number of daughter docs with this code:
[[DLMenu? 
&parents=`2`
&countChildren=`1` 
&showParent=`1` 
&outerTpl=`@CODE:[+wrap+]` 
&parentRowTpl=`@CODE:[+count+]` 
]]

DLMenu works great, but its main use is building menu html-code. If you only need to get the number of daughter docs, you may find DLMenu isn't very convenient.

Moreover, DLMenu can count "the amount of the direct children of all the resources". Direct children only, but DocCount can count all of the nesting levels.

**Comment by 64j** [comment]
```php
getChildIds($id, $depth = 10, $children = array())
```
https://github.com/evolution-cms/evolution/blob/1.4.x/manager/includes/document.parser.class.inc.php#L3092

**Comment by AgelxNash** [comment]
It's simple snippet based on DocLister
```php
$params = is_array($modx->event->params) ? $modx->event->params : array();
$out = $modx->runSnippet('DocLister', array_merge($params, array('api' => 1, 'JSONformat' => 'new')));
$out = json_decode($out);
return isset($out->total) ? $out->total : 0;
```
Now, you can run ```[!DocCount? &idType=`parents` &parents=`2` &depth=`2` &addWhereList=`template=0`!]```

+ All arguments documented
+ Supports filtering
+ Supports nested documents
+ No need create new base snippet

**Pull request closed without merging**
