### PR TITLE
Stacked table cells on small screens

### PR DESCRIPTION
**Pull request by pmfx**
Below 568px screen width, table cells of main fields, TVs and resource settings are stacked.

### CODE REVIEW

**Comment by pmfx** [comment]
zrzut 2018-05-03 17 59 58

zrzut 2018-05-03 18 00 27

**Comment by bossloper** [comment]
Suggest it could be made more inclusive so it stacks template variable tabs and system configuration page etc.
I tried which seems to work ok, though might be too general!?:
`.sectionBody td, .sectionBody th {
display:block!important;
width:100%!important;
}`

**Comment by pmfx** [comment]
Updated so it includes system settings too.

**Comment by 64j** [comment]
My opinion.
You did not start from that.
Start with this https://github.com/evolution-cms/evo-ui-kit

**Comment by pmfx** [comment]
So, we are not merging this one? I think of it as as a temporary solution before EVO UI kit is developed.

**Comment by 64j** [comment]
I have shown that there are more global tasks that can take more work.
And with this, as you want.

**Comment by pmfx** [comment]
OK, thanks.

**Pull request merged**
