### PR TITLE
Icons and restyling Extras list

### PR DESCRIPTION
**Pull request by fourroses666**

### CODE REVIEW

**Comment by Dmi3yy** [comment]
I add new param deprecated (use hidemenu in extras)

can you plz add bage for that in module

https://take.ms/wl4LT

**Comment by fourroses666** [comment]
Don't know what you mean by hidemenu.

At the moment it seems there are no deprecated Extras but that will be changed soon?

**Comment by Dmi3yy** [comment]
I extras admin panel i use this params for depricated 

https://take.ms/b595t  - you can see in json  depricated already present

**Comment by fourroses666** [comment]
Yes, sorry didn't see. Was expecting to have AjaxSearch deprecated and didn't scroll any further. 👍

**Pull request merged**
